#!/bin/bash
cd
sudo pacman -S terminator
sudo pacman -S thunar
sudo pacman -S lxappearance
sudo pacman -S neofetch
sudo pacman -S fortune-mod
sudo chmod +x paruSetup miscSetup braveSetup i3Setup lightdmSetup fishSetup
sudo ./paruSetup
sudo ./miscSetup
sudo ./braveSetup
sudo ./i3Setup
sudo ./lightdmSetup
sudo ./fishSetup
echo Setup COMPLETE!
