#!/bin/bash
cd
sudo pacman -S terminator
sudo pacman -S thunar
sudo pacman -S lxappearance
sudo pacman -S neofetch
sudo pacman -S fortune-mod
sudo mkdir ~/.vim
sudo mv archPostInstall/vim ~/.vim
sudo chmod +x paruSetup miscSetup braveSetup i3Setup lightdmSetup fishSetup
echo "Launching paruSetup"  
sudo ./paruSetup
echo "paruSetup complete!"  
echo "Launching miscSetup"  
sudo ./miscSetup  
echo "miscSetup complete!"  
echo "Launching braveSetup"    
sudo ./braveSetup  
echo "braveSetup complete!"  
echo "Launching i3Setup"  
sudo ./i3Setup  
echo "i3Setup complete!"  
echo "Launching lightdmSetup"  
sudo ./lightdmSetup  
echo "lightdmSetup complete!"  
echo "Launching fishSetup"  
sudo ./fishSetup  
echo "fishSetup complete!"  
echo "Setup COMPLETE!"
